### ISSUE TITLE
Generic FromData/ToData

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-browser-tx#165]
Implement generic versions of `ToData`/`FromData`. 

To discuss: what's the algorithm for packing/unpacking records and sum types? I guess we can pack records into `List PlutusData` , but enums? `Constr BigInt (Array PlutusData)` exists for that as far as I understand, but It's not clear how it's done, do we need to store all the alternatives?

This is not a critical feature.

**Comment by klntsky** [comment]
Note that having this at least for records would be a serious productivity boost. It's also a low handing fruit in comparison to sum types.

One problem to consider though: we can only encode bytestrings to PlutusData (i.e. we disallow characters outside of 0-255 range), but record fields can contain unicode, so we should either: 

- encode fields as *unicode-as-bytes* 
- make a type class for strings consisting of 0-255 characters that constrains usable record fields. This should be solvable theoretically - we have [`Cons`](https://pursuit.purescript.org/builtins/docs/Prim.Symbol#t:Cons) for type-level strings, so we can just enumerate all allowed characters and iterate over a string.

**Comment by bladyjoker** [comment]
Hi @klntsky, I explored this topic a bit and here's couple of notes, remarks and questions:

- I'd propose we bump up the priority of this GH ticket as the alternative is a lot of manual work (~30 types in Cardax)
  - **Q**: Perhaps I'm misreading the intention of the ticket, I'm assuming you want to have Haskell ToData/FromData compatibility?
- PlutusData encodings as [generated by Haskell](https://github.com/input-output-hk/plutus/blob/1f31e640e8a258185db01fa899da63f9018c0e85/plutus-tx/src/PlutusTx/IsData/TH.hs#L133) must be identically performed by Cbtx `genericToData`.
  - **NOTE**: Because `makeIsDataIndexed` is used we can't have `an algorithm` for determining `constructor indices` as they are specified manually/arbitrarily by the users.
  - **Q**: Perhaps in the haskell code that uses purescript-bridge to generate Purs types, we can inspect the TH generated clauses and extract the constructor indices for each type?
  -
