### ISSUE TITLE
Add serialization-lib fork to nix

### ISSUE THREAD

**Issue by klntsky** [Plutonomicon/cardano-browser-tx#45]
We need https://github.com/SundaeSwap-finance/cardano-serialization-lib available in node_modules before #44 can be merged. The upstream version of serialization-lib diverges from it enough to break the test suite.

**Comment by ngua** [comment]
By far the easiest way to solve this was to just fork Sundae's fork and then publish it to NPM. The build system is pretty complex and it would be quite a pain to try to wrap the whole thing in a Nix derivation instead of just getting it from NPM

I forked the fork and published: https://www.npmjs.com/package/@ngua/cardano-serialization-lib-nodejs (also published the browser build target)
